[package]
name = "enshrinken"
version = "0.1.0"
authors = ["Aaron Gallagher <_@habnab.it>"]

[dependencies]
byteorder = "*"
pom = "1"
rand = "*"

[dependencies.ring]
version = "*"
features = []
default-features = false
